# Generated by Django 2.2.6 on 2019-12-25 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('from_city', models.CharField(max_length=30)),
                ('to_city', models.CharField(max_length=30)),
                ('flightName', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=30)),
                ('seat', models.CharField(max_length=100)),
                ('price', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('destription', models.TextField(blank=True, null=True)),
                ('booker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_booker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
