# Generated by Django 3.0 on 2019-12-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=30)),
                ('from_place', models.CharField(max_length=30)),
                ('to_place', models.CharField(max_length=30)),
                ('depart_at_from', models.TimeField()),
                ('arrival_at_to', models.TimeField()),
                ('seat_no', models.IntegerField()),
                ('available', models.IntegerField()),
                ('collected', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_seats', models.IntegerField()),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
    ]
