# Generated by Django 3.0 on 2019-12-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_flight_status_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flight_status',
        ),
        migrations.DeleteModel(
            name='reservation',
        ),
    ]
